### ISSUE TITLE
capabilities

### ISSUE THREAD

**Issue by elvis13-prog** [ZenulAbidin/Kangaroo-256#4]
Tell me which version of CUDA to use for UBUNTU 20.04?
Maybe you will release Kangaroo-256 for Windos10?

**Comment by siupune** [comment]
use cuda 11.2

**Comment by ZenulAbidin** [comment]
Kangaroo-256 has been built against CUDA 11.2 but *might* work on never versions, or slightly older 11.x or 10.x versions, but these haven't been tested yet.

Regarding a Windows binary, that is something I plan to do sometime when I get some free time from work.

**Comment by ZenulAbidin** [comment]
Closing this unless there's another inquiry about this.

**Comment by elvis13-prog** [comment]
Installed CUDA 11.2
I run ./kangaroo-256 -gpu in.txt
In terminal: GPU code not compiled, use -DWITHGPU when compiling
???how to fix?
